### 일반 문자열로 응답받기
GET localhost:8080/kids-string
Content-Type: application/json

### 자바 객체로 응답받기
GET localhost:8080/kids-java-object
Content-Type: application/json

### 리스트로 응답받기
GET localhost:8080/kids-list
Content-Type: application/json

### 파일에서 프롬프트 템플릿 불러오기
GET localhost:8080/kids-template?genre=history
Content-Type: application/json

### 파일에서 프롬프트 템플릿 불러오기 - 리스트
GET localhost:8080/kids-template-list?genre=history
Content-Type: application/json